# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 16:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('shop_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('comment', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Expense')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAccountCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('comment', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='JournalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('comment', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAccount',
            fields=[
                ('acc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget.Acc')),
            ],
            bases=('budget.acc',),
        ),
        migrations.CreateModel(
            name='ExpenseAccount',
            fields=[
                ('acc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget.Acc')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.ExpenseCategory')),
            ],
            bases=('budget.acc',),
        ),
        migrations.CreateModel(
            name='IncomeAccount',
            fields=[
                ('acc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget.Acc')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.IncomeCategory')),
            ],
            bases=('budget.acc',),
        ),
        migrations.CreateModel(
            name='LiabilityAccount',
            fields=[
                ('acc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget.Acc')),
            ],
            bases=('budget.acc',),
        ),
        migrations.CreateModel(
            name='MoneyAccount',
            fields=[
                ('acc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget.Acc')),
            ],
            bases=('budget.acc',),
        ),
        migrations.AddField(
            model_name='journalrecord',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Acc'),
        ),
        migrations.AddField(
            model_name='journalrecord',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget'),
        ),
        migrations.AddField(
            model_name='bank',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget'),
        ),
        migrations.AddField(
            model_name='acc',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget'),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='acc_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_outgoing', to='budget.MoneyAccount'),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='acc_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_incoming', to='budget.MoneyAccount'),
        ),
        migrations.AddField(
            model_name='moneyaccount',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Bank'),
        ),
        migrations.AddField(
            model_name='moneyaccount',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.FinancialAccountCategory'),
        ),
        migrations.AddField(
            model_name='income',
            name='income_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.IncomeAccount'),
        ),
        migrations.AddField(
            model_name='income',
            name='money_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.MoneyAccount'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='expense_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.ExpenseAccount'),
        ),
        migrations.AddField(
            model_name='expense',
            name='money_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.MoneyAccount'),
        ),
    ]
