# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20160313_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalrecord',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
