# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_journalrecord_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialBalance',
            fields=[
                ('eventbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget.EventBase')),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Acc')),
            ],
            bases=('budget.eventbase',),
        ),
    ]
