# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_initialbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
