# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 19:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='note',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
