# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20160220_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='parent_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note'),
        ),
    ]
