# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20160220_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content_html',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='note',
            name='content_markdown',
            field=models.TextField(default=''),
        ),
    ]
