# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20160222_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
