# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20160222_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='content_html',
            field=models.TextField(default='', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='content_markdown',
            field=models.TextField(default='', null=True),
        ),
    ]
